language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
script:
- npm run build
- npm test
deploy:
  provider: heroku
  api_key:
    secure: H5EXBDiNVDq5J1wEppTyZXR78mRegl4sWQvvjnYPgYU2xnh4VIJNyU+fUh1vMXe0BA9Prw12wr+e8BGnjoCajMf4FaRrNQTciTWlxWVjFuMqjdUZjPZiQw6tkOqvXdVK27OgHFmFVrVTE+d7+gqJgcHqJlIzwjq3rx0pJyzRFH8WdzmaCJZY1dYek/K0eR6CYncx2kP5im+YDJzdvxIBDWE4+7wzx2ShIgYGR0fIoeCx+x9yc/QTiHZw/yywA3qS65aQzO4VAGJbADIEpp08ejRoqvhty8V6ROK7vrLN9rYE4EDV1BKT6JM/ECqkzrtY3JCbEuSbj1c77ENi/O1QPyKnzMJ3r0X4LSvLT2Y2cBiQsTMFXLNsDoWZ+DNRfbxYRzNxM1Lb2qeONz4FEz4Dw6chnEoxIdrnjAOeTrwgwsohdxnHZEGKOhte2EYNFH/iX4eF9DEpCOD3dzTaDXXXv6YwPTBMw/WBQmVgwKCzQ9vljJzv7nrcPm3lfIdmTFmCHwUd8TCSDkV1u6q53UBK6w52gZaFzqX62ipynMox6i4njVD3/QaEeD8SJI++moDL94pmJiQOwayxGdEFSsc1c/lLG3vhR1dOzDzqhLurbCoyVlO4VMLsnapX+RT4WEOt//Zw27OODQ6/7kKm3O3yusRvhH1gkr5s4rgkQiC/nBc=
  app: pet-hub
  on:
    repo: tomasdoh/PetHub-frontend
    branch: master
  skip_cleanup: true
