language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
script:
- npm run build
- npm test
deploy:
  provider: heroku
  api_key:
    secure: UG5wWII4wTxOucY+Qc0q3rS5pKzxb6j0bVSpXRQzlQr1FBgQQHTUnFbKsup4J6HaoiUimMjdF/OxkhHML79IpzTdrkanZpD01wAz4rZGdNsMtk6MCiwfimHeIS7535sUQBThYUHVMZTbtuG/IsPIQ6CQz+qOsVzJcgeACopVr6fLFGKcE/anDUjA0kK/OLqiL9VT7YKJmccYlWgW5j22M2CrCAAk1OJSaEUr7x15N9WJMGsfzUC7QQyTS1bu9vo2lBplRMZyTqXjmsjMNT/sDqq+CxurWVU8mjAJCCUU28JRHCMDAA5c1mqmhLA4vVZP1+zKcEEojY21ybtfrdLVvJblcrnpaeJLuI8VJTIgoxqvpvU5y5C8/rzZhZUcSaYv9t3e4+Uqz7xuz3/Yc04Bw6NuERNUZLtdKY30ycaHOMD4QEQM0M43QE4+Lv1BzLKTETi7Vml9CnbVBSS1Qtg/Xa4mXsssa9kW4R/xcDKV7wOVjZ3++3xL77xxHEN3WFJqlO3uGCH1XfS/TldUtgSVwUKqAyP90YIRDGLg9t2+/QBYmkpFTgGG9pD30TUGRI/4pty3+jw9uQZ3DxTseRW4twXgpnYRAFdztkAvwhHOsR3OKbA+BfSCwWQzFQIRMTtbdKmiQziCWy3/GpBwRRZpGVaFq3/u2DHGm6ZpiUTWyc0=
  app: pet-hub
  on:
    repo: tomasdoh/PetHub-frontend
    branch: master
  skip_cleanup: true
