language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
script:
- npm run build
- npm test
deploy:
  provider: heroku
  api_key:
    secure: TyHgnu7A+BUYLwLVxy2Vdp5RmXh3HJKoWe17Nm4O3lufpYnviRP0gY0UT+fNqlwWrtMIROhIcVMKZDQDGkS/act1kq0zastmlOPTL99scBd8IFjiDvh8hr0NxiiArP8YD0WoAlc3M7jAQyOus/a9YUb1QRe77i/DgZbbokWxJrYz/EMpVspimuiyZ4QnoJL6qwXZ8YsdBmwGCTaV1ZsRILn0yU41gnjMPELK6/kpNTrgv1PobAn6zyz7Lfm2T6BCc8+za/RpXwHHLEq2mx4ZQm61zJnECCkTnI6jCte6hZWrBa8lgz6VWOaQvUTJWLq27WTNYZ4pykC7F7BbXOcJM8rF8Xecpu1RIrKPO7nfjnCDYXwnyYwwqFYZZzy1PjSC9YYzGa67VYLFV+g7E31ODI1cfIsjttpB458/J4iNEoZGfN49t9NxiEKhxY18/D48TP/O5l4IYMy/URcRU2Uh9/6BWIZjj0bPM921CN1femeCZQAKD0008telqpLrCVMnQudcsDCm7suUKe9ynWu80s9xDx5OY7bp3Jt+3mkJ2JF7WUwi1AiFbksgDU27ZWTUNg9trsXTdcA6/+wB8ad3wkfsK8uasUYgejmdvKPZKZQwsWpFh1aaDQPP7JWbISU2+hWNsyC7WJ/YRQwcuxpR69VrEdoGBEh+fq0kyXowRIg=
  app: pet-hub
  on:
    repo: tomasdoh/PetHub-frontend
    branch: master
  skip_cleanup: true
