language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
script:
- npm run build
- npm test
deploy:
  provider: heroku
  api_key:
    secure: lcGoihBtX1wtcPSnsjb4QfYvoWrFex/mS3KBLtx1A/6vWobWdwt/Yr+pNnwN70T7TSrrSG7SOTS0jK6p1gzDRqi1v82xLmNfEWf0b6KsR40zlG2GDdH5wme9pgs7t9tGqT8u7wSayWPHKjBQ8aJbIgbY2pOAe0ghFwRd+9TnFaT/XnIjcBfbSdgj5nfED7K/4GtSqm7DcDVmMUcKLSQ/YAbTuxnQr8b0PSar+aH+DiuzYt5CeyQtT8s28Vipz6wYAhHk6HgyEUJuVLeutMgo5wUG29sDgoM9T3yM+EMCjpjN7xgLrTMDaj5BuzJ9xowLt+xN6vilg64/iBB3hAyNZH+mccFCf+NqsJDloHmpH7IfxBFTeyEUMmzO06doRrWA8YhvqNQmB6b92YADAg0OzdiLTXBtT1JggSK4aZFZdSaGGz2HeqwblzpoJIF7JInPkfrahEo0RX/wjyWA0lpY+wkxswMqKYgqiYnmAzhQNLqUUaxY7mzW820Ng14EBef9BPEUHP7cCEjhza7YD1ncjpGp4HvghtmW2nTP+mpAZyPLlg3H15p6hk9Cp4CDqhpmzTHafZd4GVLELomdf1zYXaSXBYx9gTJSHC9d8uesPoLPcrjaGqO3ylrhcT1SuYcGVAtN1rgt0pm4d64r4+MezdxSbeBV70N+tV2M9ZijwSE=
  app: pet-hub
  on:
    repo: tomasdoh/PetHub-frontend
    branch: master
  skip_cleanup: true
